### ISSUE TITLE
Wiki update for: 10 TypeDB Loader as Executable CLI

### ISSUE THREAD

**Issue by andy-symonds** [typedb-osi/typedb-loader#68]
Hi Folks,
The current wiki on running [TypeDB Loader as Executable CLI](https://github.com/typedb-osi/typedb-loader/wiki/10-TypeDB-Loader-as-Executable-CLI) doesn't work for me. There appears to be a missing dash and an extra comma in the command. Any chance of updating the Wiki accordingly to help new users?

It works for me when I use the following (using macOS Ventura 13.1 on Apple M1 Max, however, also had the same issue on an Intel Mac last year):
```
./bin/typedb-loader load \
        -tdb localhost:1729 \
        -c /path/to/your/config.json \
        -db databaseName \
        -cm
```
Currently, it states:
```
./bin/typedbloader load \
        -tdb localhost:1729, \
        -c /path/to/your/config.json \
        -db databaseName \
        -cm
```
Cheers,
Andy

**Comment by flyingsilverfin** [comment]
Thanks for notifying! Updated :)
