### ISSUE TITLE
Typo in documentation for cli command to fire up loader

### ISSUE THREAD

**Issue by muhammadbasitobaid** [typedb-osi/typedb-loader#73]
Hi There, I've encountered a typo while going through the documentation:
https://github.com/typedb-osi/typedb-loader/blob/master/README.md#migrate-data
the command fails if you copy it as it is, removing the comma "," after the port number (after -tbd flag), it works fine.

**Comment by flyingsilverfin** [comment]
Thank you for the report! Would you like to submit a little Pull request to fix this issue?

**Comment by flyingsilverfin** [comment]
Ok nevermind, it was so small I just did it directly! Thank you!
